INSERT INTO MOTSON.PREDICTIONS_AWAY
SELECT 
	lp.`SEASON`,
    lp.`DIVISION`,
    lp.`FIXTURE_DATE`,
    lp.`HOME_TEAM`,
    lp.`AWAY_TEAM`,
    lp.`METHOD`,
    lp.`AWAY`,
    lp.`CONFIDENCE`
FROM `MOTSON`.LOAD_PREDICTIONS_AWAY lp
WHERE 
   NOT EXISTS
   (SELECT 'x'
    FROM MOTSON.PLAYED_FIXTURES pf
    WHERE pf.SEASON = lp.SEASON
    AND pf.DIVISION = lp.DIVISION
    AND pf.HOME_TEAM = lp.HOME_TEAM
    AND pf.AWAY_TEAM = lp.AWAY_TEAM
    AND pf.FIXTURE_DATE = lp.FIXTURE_DATE)
AND NOT EXISTS
   (SELECT 'x'
    FROM MOTSON.PREDICTIONS_AWAY p
    WHERE lp.SEASON = p.SEASON
    AND lp.DIVISION = p.DIVISION
    AND lp.HOME_TEAM = p.HOME_TEAM
    AND lp.AWAY_TEAM = p.AWAY_TEAM
    AND lp.FIXTURE_DATE = p.FIXTURE_DATE
    AND lp.METHOD = p.METHOD)
    
    
